---
title: "City of Calgary Rainfall Data Results"

# following code is from stackoverflow - to allow for landscape stype pdf output
# https://stackoverflow.com/questions/25849814/rstudio-rmarkdown-both-portrait-and-landscape-layout-in-a-single-pdf/41945462#41945462

header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}

output:
  pdf_document: default
  classoption: landscape # does not seem to work (30-JAN-2021)
  html_notebook: default
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(printr)
library(reshape2)
library(pander)


# added 12-DEC-2020
library(lubridate)
library(scales)
library(rio)
library(knitr)
library(tinytex)
library(tidyverse)
library(ggnewscale)
library(kableExtra)
library(hydroTSM)
#library(plyr)

panderOptions('knitr.auto.asis', FALSE)

```



```{r compile raw data, eval = FALSE, include=FALSE}


# create (if necessary) 'data_out' directory
if(dir.exists('data_out') == FALSE) dir.create('data_out')


  # read the site names
  site_names<-read.table('Site Names/Site_Names_and_Ground_Elevations.csv',sep=",",header=TRUE,stringsAsFactors = FALSE)
 
  # extract a vector of the site names
  site_names<-as.character(site_names$Site.Name)
  
  # shorten to first two 2 site names - testing / optional
  site_names <- site_names[1:2]

  # get the names of the raw data subfolders
  subfolder_names<-dir('data_in',full.names = TRUE)
 
  # shorten to first two years of data - testing / optional
  subfolder_names <- subfolder_names[1:2]
  
  
  ## ## ## Start of nested loop ## ## ##
  
  # enter loop along the site names (e.g. 'S01', 'S02', etc.)  
  for (j in seq_along(site_names)) {
  
  # enter loop along the subfolder names (e.g. 1988, 1989, etc.)
  for (i in seq_along(subfolder_names)) {
  
  name<-site_names[j]
  
  # strip the site names from the raw file names in each subfolder
  
  temp_names<-strtrim(dir(subfolder_names[i]),3)
 
  # check to see if the 'name' passed to the function exists in the trimmed file names
  if(name %in% temp_names)  {
    
 
  # the name of the matched file
  file_match_char<-list.files(subfolder_names[i],pattern = name)
  #print(file_match_char)
  
  # the full path pf the matched file
  file_match_path<-file.path(subfolder_names[i],file_match_char)
  #print(file_match_path)
  
   # reference the full path and the input file name using file.path
  infile<-file_match_path
  
  # read raw rainfall data using 'read.table'
  #rainfall_data<-read.table(infile,sep="\t",header=FALSE,skip=3,stringsAsFactors = FALSE)
  
  # read raw rainfall data using 'read_tsv'
  rainfall_data<-read_tsv(infile,col_names = FALSE,trim_ws = TRUE,skip = 3)
  
  colnames(rainfall_data)<-c("Date","Hour.Minute.Seconds","Rainfall")
  
  # create a column of Site.Name data
  Site.Name<-rep(name,nrow(rainfall_data))
 
  # get the discrete date - time components
  Year<-year(rainfall_data$Date)
  Month<-month(rainfall_data$Date)
  Week<-week(rainfall_data$Date)
  Day<-mday(rainfall_data$Date)
  Hour<-hour(rainfall_data$Hour.Minute.Seconds)
  Minute<-minute(rainfall_data$Hour.Minute.Seconds)  
  DOY<-yday(rainfall_data$Date)
  Cumulative.Yearly.Rainfall<-cumsum(rainfall_data$Rainfall)
  
  # column bind the data and the date info
  temp_df<-cbind(Site.Name,rainfall_data,Cumulative.Yearly.Rainfall,Year,Month,Week,Day,Hour,Minute,DOY)
 
  # use mutate to add Date-Time from components
  # Reminder: the time zone setting only affects the value when printing
  temp_df <- temp_df %>% mutate(Date.Time=make_datetime(Year,Month,Day,Hour,Minute,tz = "America/Denver"))
  
  # create empty list, on first pass
  if(i == 1) raw_data_list<-list(NULL)
  
  # build a list of the raw data for each site (see Hadley book, page 319)
  raw_data_list[[i]] <- temp_df
 
  }   
    
  else {
    
    print ("No filename match in that subfolder")
  }  
    
    } # end of 'seq_along(subfolder_names)'
    
 
  # create a directory to save the .CSV files
  CSV_master_folder_5_min<-paste0('data_out',"/MASTER_CSV_5_min")
 
  # create (if necessary) 'data_out/MASTER_CSV_5_min' directory
  if(dir.exists(CSV_master_folder_5_min) == FALSE) dir.create(CSV_master_folder_5_min)
  
  # create a file name to save the files for each site
  CSV_file_name<-paste0(name,"_5_min.csv")
  CSV_outfile<-file.path(CSV_master_folder_5_min, CSV_file_name)
    
  # convert the 'raw_data_list' list to a dataframe using ldply from 'plyr' package
  raw_data_XX<-plyr::ldply(raw_data_list,rbind)
  
  # write the results to .CSV file
  write_csv(raw_data_XX,CSV_outfile)   
  
  rm(raw_data_XX)  
  
     
  } # end of 'seq_along(site_names)'
  
 
# *************************************************************


```


\blandscape
```{r site-by-site statistics and charts, echo = FALSE,include = TRUE,message=FALSE,warning=FALSE,results = 'asis'}

  # seq along the .CSV files; generate basic summary stastics

    # the names of the full CSV files
    csv_names<-list.files('data_out/MASTER_CSV_5_min')
    
    # print(csv_names)
    
     for (i in seq_along(csv_names)) {
   
      # specify the CSV directory location and path to read the CSV file
      CSV_folder<-'data_out/MASTER_CSV_5_min'
      CSV_infile<-file.path(CSV_folder, csv_names[i])
      
      
      # create site name prefix
      site_prefix<-strtrim(csv_names[i],3)
      # print(site_prefix)
      
      # create directory to save statistics results - 5 minute data
      stats_folder_1<-'data_out/Stats_Summary_1'
      
      # create (if necessary) directory - ** first part
      if(dir.exists(stats_folder_1) == FALSE) dir.create(stats_folder_1)
      
      # create directory to save statistics results
      stats_folder_2<-'data_out/Stats_Summary_2'
      
      # create (if necessary) directory - ** first part
      if(dir.exists(stats_folder_2) == FALSE) dir.create(stats_folder_2)
      
       # create directory to save statistics results
      stats_folder_3<-'data_out/Stats_Summary_3'
      
      # create (if necessary) directory - ** first part
      if(dir.exists(stats_folder_3) == FALSE) dir.create(stats_folder_3)
      
      
      
      
      # read the rainfall data for one site using 'read_csv'
      rain_5_min<-read_csv(CSV_infile,col_names = TRUE)
      
      # 5 minute rainfall statistics - ** not used but keep for now **
      
      # stats_5_min <- rain_5_min %>% summarize(mean=mean(Rainfall),
      #                                            sd=sd(Rainfall),
      #                                            min=min(Rainfall),
      #                                            Q1=quantile(Rainfall,probs=0.25),
      #                                            median=median(Rainfall),
      #                                            Q3=quantile(Rainfall,probs=0.75),
      #                                            max=max(Rainfall),
      #                                            CV_pct=(sd/mean)*100,
      #                                            total.count=n(),
      #                                            n.valid=sum(!is.na(Rainfall)),
      #                                            pct.valid=(n.valid/total.count)*100)
      # 
      # print(stats_5_min)
      
      # get basic stats on the 5 minute rainfall data
      
      site.name <- rain_5_min$Site.Name[1]
      
      mean <- mean(rain_5_min$Rainfall,na.rm = TRUE)
      
      sd <- sd(rain_5_min$Rainfall,na.rm = TRUE)
      
      max <- max(rain_5_min$Rainfall,na.rm = TRUE)
      
      n.total <- nrow(rain_5_min)
      
      n.NA <- sum(is.na(rain_5_min$Rainfall))
      
      pct.missing <- (n.NA/n.total)*100
      
      n.non.zero <- nrow(subset(rain_5_min,Rainfall > 0))
      
      pct.non.zero <- (n.non.zero/n.total)*100
      
      n.May.to.Sept <- rain_5_min %>% filter(Month >= 5 & Month <= 9)
      
      n.May.to.Sept <- nrow(n.May.to.Sept)
      
      pct.May.to.Sept <- (n.May.to.Sept/n.total)*100
      
      # rbind the results
      
      stats_5_min <- rbind(mean,sd,max,n.total,n.NA,pct.missing,n.non.zero,pct.non.zero,n.May.to.Sept,pct.May.to.Sept)
      
      stats_5_min_df <- data.frame("Site.Name"=site.name,
                                    "mean"=mean,
                                    "std.dev"=sd,
                                    "max"=max,
                                    "n.total"=n.total,
                                    "n.NA"=n.NA,
                                    "pct.missing"=pct.missing,
                                    "n.non.zero"=n.non.zero,
                                    "pct.non.zero"=pct.non.zero,
                                    "n.May.to.Sept"=n.May.to.Sept,
                                    "pct.May.to.Sept"=pct.May.to.Sept)  
      
     
      # compile 'stats_5_min_df' results into single dataframe
      
      # note: the resulting dataframe is saved to .csv outside the current loop
      
      # assign result to the dataframe, only on the first pass
      if(i == 1) {
         
      # create empty dataframe to store the results
      stats_5_min_compiled<-data.frame(NULL)

      stats_5_min_compiled <- stats_5_min_df
      }

      # iteratively rbind the results into a dataframe, starting at the second iteration
      if(i > 1) {
        stats_5_min_compiled <- rbind(stats_5_min_compiled,stats_5_min_df)
      }
      
     
      # filter for the May to September rainfall
      rain_5_min_may_sept <- rain_5_min %>% filter(Month >= 5 & Month <= 9)
     
      # get the hourly rainfall
      # Note: you have to add 'ungroup()' before the select command to extract only the hourly.rainfall *** 
     
       rain_hourly <- rain_5_min_may_sept %>% group_by(Year,Month,Day,Hour) %>% summarize(summary.rainfall=sum(Rainfall)) %>% ungroup() %>% select(summary.rainfall)
       
       # print(rain_hourly)
      
      # get the daily rainfall
      rain_daily <- rain_5_min_may_sept %>% group_by(Year,Month,Day) %>% summarize(summary.rainfall=sum(Rainfall)) %>% ungroup() %>% select(summary.rainfall)
      
      # get the weekly rainfall
      rain_weekly <- rain_5_min_may_sept %>% group_by(Year,Month,Week) %>% summarize(summary.rainfall=sum(Rainfall)) %>% ungroup() %>% select(summary.rainfall)
      
       # get the monthly rainfall
      rain_monthly <- rain_5_min_may_sept %>% group_by(Year,Month) %>% summarize(summary.rainfall=sum(Rainfall)) %>% ungroup() %>% select(summary.rainfall)
      
       # get the yearly rainfall
      rain_yearly<- rain_5_min_may_sept %>% group_by(Year) %>% summarize(summary.rainfall=sum(Rainfall)) %>% ungroup() %>% select(summary.rainfall)
      
      # convert to dataframe before using map(smry)
      
      rain_hourly <- as.data.frame(rain_hourly)
      rain_daily <- as.data.frame(rain_daily)
      rain_weekly <- as.data.frame(rain_weekly)
      rain_monthly <- as.data.frame(rain_monthly)
      rain_yearly <- as.data.frame(rain_yearly)
     
      # create a list of the rain interval results
     
       rain_list_1 <- list(rain_hourly,rain_daily,rain_weekly,rain_monthly,rain_yearly)
       
      # try using 'map' instead of seq_along 'rain_list_1'
      
      stats_df_list <- rain_list_1 %>% map(hydroTSM::smry)
       
      # use 'bind_cols' to combine the list of dataframes to one dataframe
      
      stats_df_bind_cols <- bind_cols(stats_df_list)
      
      # add column names
      colnames(stats_df_bind_cols) <- c("Hourly","Daily","Weekly","Monthly","Yearly")
      
      # add Site.Name to the dataframe - this maybe be optional - under review
      
      Site.Name <- rep(site_prefix,nrow(stats_df_bind_cols))
      
      stats_df_bind_cols<- data.frame(Site.Name,stats_df_bind_cols)
      
      view(stats_df_bind_cols)
      
      # create a file name to save the files for each site
      CSV_file_name<-paste0(site_prefix,"_stats_summary_hourly_to_yearly.csv")
      CSV_outfile<-file.path(stats_folder_1, CSV_file_name)
        
       # write the results to .CSV file
       write.table(stats_df_bind_cols,CSV_outfile,sep=",",col.names=NA,row.names=TRUE)
      
     
      
  # create yearly rainfall bar chart - descending order
  
  # summarize to DAILY / MONTHLY / ANNUAL / MONTHLY AVERAGE data
  # filter for the months May to September (05 - 09) 
  daily_rainfall<- rain_5_min %>% group_by(Site.Name,Year,Month,Date) %>% filter(Month >= 5 & Month <= 9) %>% summarize(daily.rainfall=sum(Rainfall,na.rm=TRUE))
  monthly_rainfall<- rain_5_min %>% group_by(Site.Name,Year,Month) %>% filter(Month >= 5 & Month <= 9) %>% summarize(monthly.rainfall=sum(Rainfall,na.rm=TRUE))
  annual_rainfall<- rain_5_min %>% group_by(Site.Name,Year) %>% filter(Month >= 5 & Month <= 9) %>% summarize(annual.rainfall=sum(Rainfall,na.rm=TRUE))
  monthly_rainfall<- as_tibble(monthly_rainfall)
  monthly_average_rainfall<- monthly_rainfall %>% group_by(Site.Name,Month) %>% summarize(average.monthly.rainfall=mean(monthly.rainfall,na.rm=TRUE))
     
  # print(annual_rainfall)
  
  
  # plot May - Sept 'annual' rainfall data - plot in descending order
  
  # create chart title (dynamic)
  chart_title<-paste0("Rain Gauge"," ",site_prefix," ", "Total May-Sept. Rainfall - Descending")
  
  # create chart PNG outifle name (dynamic)
  outfile_name<-paste0(site_prefix," - ", "May - Sept Rainfall - Desc.png")
  
   # specify directory name
    PNG_folder_name<-stats_folder_3
  
  p1<-ggplot(data=annual_rainfall, aes(x = reorder(Year, -annual.rainfall),y=annual.rainfall,fill=Year)) +
    geom_bar(stat = "identity",position=position_dodge()) +
    theme(axis.title.x = element_text(size = 12),axis.text.x = element_text(angle=45,hjust=1)) +
    theme(axis.title.y = element_text(size = 12)) +
    ylab("Rainfall (mm)") +
    scale_y_continuous(limits = c(0,500)) +
    xlab("") +
    guides(fill=FALSE) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(plot.title = element_text(size = 14)) +
    ggtitle(chart_title)
  outfile<-file.path(PNG_folder_name,outfile_name)
  ggsave(outfile,p1,width= 6, height=3.708, dpi=600,units=c("in"))
  print(p1)
  rm(chart_title,outfile_name,PNG_folder_name,outfile) #outfile variable is used again later
  
  
   
  } # end of seq_along(csv_names)


      # with 'stats_5_min_compiled': save .csv file
     
      # create file path and name to save results
      temp_name<-paste0(stats_folder_2,"/stats_5_min_all_sites.csv")
      
      # write the above results to .CSV files
      write.table(stats_5_min_compiled,temp_name,sep=",",col.names=TRUE,row.names=FALSE)


  # create table using kable
  
  # create dummy table caption
  table_caption<-'Statistics Summmary: 5 minute Data All Sites'

  # read the saved .CSV file
  stats_table<-read.table('data_out/Stats_Summary_2/stats_5_min_all_sites.csv',sep=",",header=TRUE,stringsAsFactors = FALSE)


  # stats_table %>% knitr::kable(caption = table_caption, digits = 3) %>% kableExtra::kable_styling(bootstrap_options = "striped")
  stats_table %>% knitr::kable(caption = table_caption, digits = 3) %>% kableExtra::kable_styling("striped")
  

  
  # create bar chart of the 5 minute data count, all sites
      
      chart_title<-'Total 5-Minute Rainfall Data Count - by Site'
      
      # create chartPNG outifle name
      outfile_name<-'n_total_5_minute_data_by_site.png'
      
      # specify directory name
      PNG_folder_name<-stats_folder_2
      
    p1<-ggplot(data=stats_5_min_compiled, aes(x = Site.Name,y = n.total,fill=Site.Name)) +
        geom_bar(stat = "identity",position=position_dodge()) +
        theme(axis.title.x = element_text(size = 12),axis.text.x = element_text(angle=45,hjust=1)) +
        theme(axis.title.y = element_text(size = 12)) +
        ylab("Data Count") +
        # scale_y_continuous(limits = c(0,500)) +
        xlab("") +
        guides(fill=FALSE) +
        theme(plot.title = element_text(hjust = 0.5)) +
        theme(plot.title = element_text(size = 14)) +
        ggtitle(chart_title)
      outfile<-file.path(PNG_folder_name,outfile_name)
      ggsave(outfile,p1,width= 6, height=3.708, dpi=600,units=c("in"))
      print(p1)
    rm(chart_title,outfile_name,PNG_folder_name,outfile) #outfile variable is used again later
  
  
    
    


  
  
   
   
``` 
\elandscape

\blandscape
```{r plot data count 5-min}

 # create bar chart of the 5 minute data count, all sites
      
      chart_title<-'Total 5-Minute Rainfall Data Count - by Site'
      
      # create chartPNG outifle name
      outfile_name<-'n_total_5_minute_data_by_site.png'
      
      # specify directory name
      PNG_folder_name<-stats_folder_2
      
    p1<-ggplot(data=stats_5_min_compiled, aes(x = Site.Name,y = n.total,fill=Site.Name)) +
        geom_bar(stat = "identity",position=position_dodge()) +
        theme(axis.title.x = element_text(size = 12),axis.text.x = element_text(angle=45,hjust=1)) +
        theme(axis.title.y = element_text(size = 12)) +
        ylab("Data Count") +
        # scale_y_continuous(limits = c(0,500)) +
        xlab("") +
        guides(fill=FALSE) +
        theme(plot.title = element_text(hjust = 0.5)) +
        theme(plot.title = element_text(size = 14)) +
        ggtitle(chart_title)
      outfile<-file.path(PNG_folder_name,outfile_name)
      ggsave(outfile,p1,width= 6, height=3.708, dpi=600,units=c("in"))
    print(p1)
    rm(chart_title,outfile_name,PNG_folder_name,outfile) #outfile variable is used again later

```
\elandscape



